algoritmo "ATV_26"
var
n1, n2: inteiro
inicio

      Escreva("Número 1: ")
      Leia(n1)
      Escreva("Número 2: ")
      Leia(n2)
      Se (N1 > N2) entao
          Escreval("O primeiro valor é o maior")
      Senao
           Se N2 > N1 entao
              Escreva("O segundo valor é o maior")
           Senao
                Escreva("Não existe valor maior, os dois são iguais")
           FimSe
      FimSe

fimalgoritmo